//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _06.ReadFromExcelFile {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SqlSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SqlSettings defaultInstance = ((SqlSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SqlSettings())));
        
        public static SqlSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
